// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about-info" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutInfoSection(): React.JSX.Element {
  return (
    <div id="about-info" data-section="about-info">
        <SectionErrorBoundary name="about-info">
              <AboutTextSplit
          title="Our Family Mission"
          descriptions={[
            "J&E Technologies is committed to accelerating the future of electric mobility by providing reliable and innovative EV charging solutions.",
            "As a family-owned company, we strive to make sustainable transportation easier for drivers, businesses, and communities through dependable technology and convenient service.",
            "Together, we are building the infrastructure for a cleaner, more connected future.",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
