// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about-info" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutInfoSection(): React.JSX.Element {
  return (
    <div id="about-info" data-section="about-info">
        <SectionErrorBoundary name="about-info">
              <AboutTextSplit
          title="Our Family Mission"
          descriptions={[
            "J&E Technologies was born from a simple belief:
A cleaner, more connected future is possible by providing reliable EV charging solutions that make electric mobility accessible for everyone.",
            "As a family-owned company, we believe the transition to electric transportation is an opportunity to create stronger communities and a more sustainable future for generations to come. Our mission is to provide dependable and convenient charging infrastructure that helps drivers, businesses, and communities confidently embrace electric vehicles.",
            "We are dedicated to delivering a seamless charging experience through innovative technology and a commitment to reliability. Every charging station we provide represents our promise to support the growing EV community and help build the infrastructure needed for a cleaner future.",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
