// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about-info" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutInfoSection(): React.JSX.Element {
  return (
    <div id="about-info" data-section="about-info">
        <SectionErrorBoundary name="about-info">
              <AboutTextSplit
          title="Our Family Mission"
          descriptions={[
            "VoltFamily was born from a simple belief: transportation should be clean, fast, and accessible for everyone.",
            "Starting as a small family-owned electrical shop, we transformed our passion for innovation into a network of reliable charging stations.",
            "Today, we are committed to building the infrastructure of the future, supporting our local community, and making the switch to electric simple and worry-free.",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
