// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Common Questions"
          title="Charging Explained"
          description="Your quick guide to our charging technology."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "What charger types do you support?",
                  answer: "We support J1772, CCS, and NACS (Tesla) standards.",
                },
                {
                  question: "How do I pay?",
                  answer: "Use our simple app or pay via credit card at the station.",
                },
              ],
            },
            {
              name: "Sustainability",
              items: [
                {
                  question: "Is my energy green?",
                  answer: "Yes, 100% of our energy is sourced from verified solar and wind farms.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
