// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features-grid" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesGridSection(): React.JSX.Element {
  return (
    <div id="features-grid" data-section="features-grid">
        <SectionErrorBoundary name="features-grid">
              <FeaturesBentoGrid
          tag="Why Choose J&E Technologies?
    "
          title="Unmatched Reliability and Service"
          description="Built on family values and a vision for a cleaner, sustainable tomorrow."
          features={[
            {
              title: "Lightning Speed",
              description: "High-powered charging stations minimizing your wait time.",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-electric-car-charging-spot_23-2149530083.jpg",
            },
            {
              title: "100% Sustainable",
              description: "Powered entirely by certified renewable energy sources.",
              imageSrc: "http://img.b2bpic.net/free-photo/solar-panel-icon-renewable-energy-symbol_53876-167295.jpg",
            },
            {
              title: "Community Focus",
              description: "Local support and reliable service you can always count on.",
              imageSrc: "http://img.b2bpic.net/free-photo/favorite-star-icon-sign-symbol-button-blue-speech-bubble-white-background-3d-rendering_56104-1179.jpg",
            },
            {
              title: "Smart Connectivity",
              description: "Real-time status updates and simple charging control.",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-woman-charging-electric-car_23-2149530093.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
