// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBrand from '@/components/sections/hero/HeroBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBrand
          brand="Powering the Future of Electric Mobility"
          description="Your trusted family-owned partner for reliable, sustainable, and innovative EV charging solutions across the community."
          primaryButton={{
            text: "Find a Charger",
            href: "/find",
          }}
          secondaryButton={{
            text: "Contact Us",
            href: "/contact",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/woman-holding-car-charger-electric-vehicle-charging-station_107420-94919.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
